name: "Question"
description: "Ask a question about a project or configuration"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "What would you like to know?"
    validations:
      required: true
