services:
  app:
    image: ghcr.io/arunoruto/beszel-agent:0.18.6@sha256:c125478e5241c3a86938c22da4f34f51c0f3684b859ebf5c07d9c286b46819c4
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - utility
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: info
      PORT: ${PORT:-45876}
      GPU: true
      KEY: $BESZELKEY
    healthcheck:
      test: ['CMD', '/agent', 'health'] # Run the health command
      start_period: 5s # Check 5 seconds after the container starts
      interval: 120s # Then check every 120 seconds after that
    labels:
      - autoheal=true
