version: '3.3'
services:
  app:
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.9.0@sha256:5b8cfa805cb60b99a9e83a2df62d41c63865a315f7ee7cfed1a78052d93650b6
    restart: unless-stopped
    volumes:
      - config:/app/data
    network_mode: host #required for auto-discovery of Android TV

volumes:
  config:
