version: '3.3'
services:
  app:
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.7.0@sha256:ff292ed53c9208ebfa7da3be7084bd863339d545a799bfefed5092396f5e8b4b
    restart: unless-stopped
    volumes:
      - config:/app/data
    network_mode: host #required for auto-discovery of Android TV

volumes:
  config:
