version: '3.3'
services:
  app:
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.10.0@sha256:f2e4c7e57f6fcb490156759bcc79561ac594675354923a71f1f034a3fe39d7de
    restart: unless-stopped
    volumes:
      - config:/app/data
    network_mode: host #required for auto-discovery of Android TV

volumes:
  config:
