version: "3"

services:
  app:
    image: emmercm/qbittorrent:5.1.4-alpine@sha256:891dee33792bb43f7529bf3a57d14788a76cdb9f7e9aa03d343a4f097707e69b
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
      - 8.8.4.4
      - 9.9.9.9
    environment:
      - TZ=$TZ
    ports:
      - ${WEBPORTQB:-8080}:8080
      - ${PORTFORWARD:-6881}:${PORTFORWARD:-6881}/tcp #Torrent Traffic
      - ${PORTFORWARD:-6881}:${PORTFORWARD:-6881}/udp #Torrent Traffic
    volumes:
      - config:/config
      - data:/data
      - ${DOWNLOADS}:${DOWNLOADS}
      - ${DOWNLOADS}:/downloads
      - ${DOWNLOADS}/incomplete:/incomplete
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8080
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true  
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
  qui:
    image: ghcr.io/autobrr/qui:v1.19.0@sha256:baa07db5326f75f8c2246703603cbe2132476c8ad0ab31c976a960cb4c4731f5
    restart: unless-stopped
    ports:
      - ${WEBPORT:-7476}:${WEBPORT:-7476}
    volumes:
      - qui:/config
    environment:
      QUI__PORT: ${WEBPORT:-7476}
      QUI__BASE_URL: ${CFURLPATH:-}/
      QUI__AUTH_DISABLED: ${DISABLE_AUTH:-false}
      QUI__IF_I_GET_BANNED_ITS_MY_FAULT: ${DISABLE_AUTH:-false}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${WEBPORT:-7476}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld} #default_tld, authenticate, bypass
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
      
       
volumes:
  config:
  data:
  qui:

