version: "3"

services:
  app:
    image: emmercm/qbittorrent:5.1.4-alpine@sha256:9d1176fca1f1640440c4cb9bca2d8c2b2fc90836fdf8c8e33f883e9e2821a2e3
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
      - 8.8.4.4
      - 9.9.9.9
    environment:
      - TZ=$TZ
    ports:
      - ${WEBPORTQB:-8080}:8080
      - ${PORTFORWARD:-6881}:${PORTFORWARD:-6881}/tcp #Torrent Traffic
      - ${PORTFORWARD:-6881}:${PORTFORWARD:-6881}/udp #Torrent Traffic
    volumes:
      - config:/config
      - data:/data
      - $DOWNLOADS:/volume1/downloads
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8080
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true  
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
  qui:
    image: ghcr.io/autobrr/qui:v1.16.1@sha256:07b6ea9572e52e8b5f70f8fb15a7c688d8d754a7616242d3ad0b21dbd5c05836
    restart: unless-stopped
    ports:
      - ${WEBPORT:-7476}:${WEBPORT:-7476}
    volumes:
      - qui:/config
    environment:
      QUI__PORT: ${WEBPORT:-7476}
      QUI__BASE_URL: ${CFURLPATH:-}/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${WEBPORT:-7476}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld} #default_tld, authenticate, bypass
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
      
       
volumes:
  config:
  data:
  qui:

