version: '3'
services:
  app:
    image: ghcr.io/linuxserver/tautulli:2.18.2@sha256:bfcd2f3f6f89d2171d161ac1780723d1633f8de3c4c993d0dc52aa9edb729e16
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - app:/config
    ports:
      - ${PORT:-8181}:8181
    restart: unless-stopped
    networks:
      - cloudflare-net
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8181
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-8181}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  app:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true

