#!/bin/sh
# Ensure dependencies are present
apk add --no-cache curl jq

echo "Checking for Proxmox Firewall Setup..."

# Step 0: Ensure the IP Set exists at the Datacenter level
curl -s -k -X POST -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
  -d "name=crowdsec_bans" \
  "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/ipset" > /dev/null

# Step 1: Check if a DROP rule for this IP Set already exists
# We look for any rule where the 'source' matches '+ipset/crowdsec_bans'
EXISTING_RULE=$(curl -s -k -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
  "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/rules" | jq -r '.data[] | select(.source == "+ipset/crowdsec_bans") | .pos' | head -n 1)

if [ -z "$EXISTING_RULE" ]; then
  echo "No firewall rule found for crowdsec_bans. Creating DROP rule..."
  # Create the rule: IN, DROP, Source: +ipset/crowdsec_bans, Enabled: 1
  curl -s -k -X POST -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
    -d "type=group" \
    -d "action=DROP" \
    -d "source=+ipset/crowdsec_bans" \
    -d "enable=1" \
    -d "comment=Auto-generated by CrowdSec Sync" \
    "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/rules" > /dev/null
else
  echo "Firewall rule already exists at position $EXISTING_RULE."
fi

while true; do
  echo "Starting Sync: $(date)"

  # 2. Fetch current active decisions from CrowdSec LAPI
  CS_BANS=$(curl -s -H "X-Api-Key: $BOUNCER_KEY" "http://localhost:${CROWDSEC_PORT:-8080}/v1/decisions" | jq -r '. // [] | .[].value // empty' | sort)

  # 3. Fetch current IPs from the Proxmox 'crowdsec_bans' IP Set
  PVE_BANS=$(curl -s -k -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
    "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/ipset/crowdsec_bans" | jq -r '.data // [] | .[].cidr // empty' | sort)

  # 4. ADD Logic
  for ip in $CS_BANS; do
    if ! echo "$PVE_BANS" | grep -q "$ip"; then
      echo "Adding $ip to Proxmox GUI..."
      curl -s -k -X POST -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
        -d "cidr=$ip" "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/ipset/crowdsec_bans" > /dev/null
    fi
  done

  # 5. REMOVE Logic
  for pve_ip in $PVE_BANS; do
    if ! echo "$CS_BANS" | grep -q "$pve_ip"; then
      echo "Removing expired ban $pve_ip from Proxmox GUI..."
      curl -s -k -X DELETE -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
        "https://localhost:${PVE_PORT:-8006}/api2/json/cluster/firewall/ipset/crowdsec_bans/$pve_ip" > /dev/null
    fi
  done

  echo "Sync complete. Sleeping 5 minutes..."
  sleep 300
done
